### PR TITLE
Add sql scripts

### PR DESCRIPTION
**Pull request by arpit-dhindsa**
Add:
- SQL scripts for each table in Synapse dedicated pool
- Linked services' json files
- credential json file

### CODE REVIEW

**Review by gopal-kannan — COMMENTED** [review]
Individual sql files with check before drop looks good to me.

**Comment by s-laugh** [comment]
A few general questions:
1. Was all this auto generated from synapse (when the connection was established)?
2. Will these scripts work in an update capacity? - If we delete the table every time, it would delete all the data collected along with it...?

**Comment by arpit-dhindsa** [comment]
The scripts were manually generated

**Comment by s-laugh** [comment]
It's been a few day's but a believe in another conversation, it was identified that this

> Will these scripts work in an update capacity? - If we delete the table every time, it would delete all the data collected along with it...?

Is actually a problem and will need a more appropriate script to handle the use cases.

**Comment by gopal-kannan** [comment]
> It's been a few day's but a believe in another conversation, it was identified that this
> 
> > Will these scripts work in an update capacity? - If we delete the table every time, it would delete all the data collected along with it...?
> 
> Is actually a problem and will need a more appropriate script to handle the use cases.

We found that visual studio code can be used to create the database project and it can be version controlled. The database project will create dacpac file (deployable code to apply database changes) which will apply the changes only. Meaning, creates missing objects and updates the definition changes like data type changes, column inclusion and exclusion etc. We can discuss in detail in our stand up meeting.

**Pull request closed without merging**
